#LoRaWAN
CONFIG_LOG=y
CONFIG_LORA=y
CONFIG_LORAWAN=y
CONFIG_POWEROFF=y
CONFIG_LORAWAN_REGION_EU868=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_NVS=y
CONFIG_LORAWAN_NVM_SETTINGS=y

CONFIG_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
#rtc things
CONFIG_I2C=y
CONFIG_RTC=y
#CONFIG_RTC_RV8803=y # 77new: enables rtc_alarm_set_time / rtc_alarm_set_callback
CONFIG_RTC_ALARM=y
CONFIG_GPIO=y